name: taskmenot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0


  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  percent_indicator: ^4.2.5
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/Logo.png

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

  uses-material-design: true

flutter_native_splash:
  color: "#FBFBFB"
  image: assets/images/Logo.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Logo-2.png
  remove_alpha_ios: true
