// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwfqJX7JWXhqnoWnrrNMZ2d3SVjy7MCM',
    appId: '1:835771101660:web:5a43a00ce935afb1a55f19',
    messagingSenderId: '835771101660',
    projectId: 'taskmenot-cb77f',
    authDomain: 'taskmenot-cb77f.firebaseapp.com',
    storageBucket: 'taskmenot-cb77f.firebasestorage.app',
    measurementId: 'G-FF8KQXZ446',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-aWynyR8obZa9kiL6qf_BK6FqZu81OmA',
    appId: '1:835771101660:android:49c8623e1fddf51fa55f19',
    messagingSenderId: '835771101660',
    projectId: 'taskmenot-cb77f',
    storageBucket: 'taskmenot-cb77f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBCzVpUDGTxhqRPE-QBn94z8WH3oJ6wY',
    appId: '1:835771101660:ios:ec0b83b3578f607ea55f19',
    messagingSenderId: '835771101660',
    projectId: 'taskmenot-cb77f',
    storageBucket: 'taskmenot-cb77f.firebasestorage.app',
    iosBundleId: 'com.example.taskmenot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBCzVpUDGTxhqRPE-QBn94z8WH3oJ6wY',
    appId: '1:835771101660:ios:ec0b83b3578f607ea55f19',
    messagingSenderId: '835771101660',
    projectId: 'taskmenot-cb77f',
    storageBucket: 'taskmenot-cb77f.firebasestorage.app',
    iosBundleId: 'com.example.taskmenot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwfqJX7JWXhqnoWnrrNMZ2d3SVjy7MCM',
    appId: '1:835771101660:web:e503b88d84d91589a55f19',
    messagingSenderId: '835771101660',
    projectId: 'taskmenot-cb77f',
    authDomain: 'taskmenot-cb77f.firebaseapp.com',
    storageBucket: 'taskmenot-cb77f.firebasestorage.app',
    measurementId: 'G-TF4CFG9SW4',
  );
}
